service:
  bloom-reports

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  tags:
    project: bloom-reports

functions:
  status-writer:
    handler: src/index.handler

resources:
  Resources:
    reportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: status-entries
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE            
        BillingMode: PAY_PER_REQUEST
          